services:
  client:
    build: ./client
    ports:
      - "4000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      MONGO_URL: mongodb://mongo:27017/mydb
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: